name: MatricesForHomalg
version: 2018.12.09
date: 09/12/2018
description: Matrices for the homalg project

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/
    - name: Martin Leuner
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/leuner.php
    - name: Vinay Wagh
      url: http://www.iitg.ernet.in/vinay.wagh/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/

GAP: ">=4.7"

needed-pkgs:
    - name: "ToolsForHomalg"
      version: ">= 2012.10.27"
      url: "http://homalg-project.github.io/homalg_project/ToolsForHomalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/MatricesForHomalg/
readme: http://homalg-project.github.io/homalg_project/MatricesForHomalg/README
packageinfo: http://homalg-project.github.io/homalg_project/MatricesForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/MatricesForHomalg-2018.12.09/MatricesForHomalg-2018.12.09.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/MatricesForHomalg-2018.12.09/MatricesForHomalg-2018.12.09.zip

abstract: The <span class="pkgname">MatricesForHomalg</span> package provides lazy evaluated matrices with clever operations for the homalg project

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
