name: GradedModules
version: 2019.09.02
date: 02/09/2019
description: A homalg based package for the Abelian category of finitely presented graded modules over computable graded rings

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io
    - name: Sebastian Jambor
      url: http://wwwb.math.rwth-aachen.de/~sebastian/
    - name: Markus Lange-Hegermann
      url: https://www.hs-owl.de/fb5/fachbereich/fachgebiete/md/team/prof-dr-markus-lange-hegermann.html
    - name: Arne Lorenz
      url: http://wwwb.math.rwth-aachen.de/~arne/
    - name: Oleksandr Motsak
      url: http://www.mathematik.uni-kl.de/~motsak/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io

GAP: ">=4.7"

needed-pkgs:
    - name: "ToolsForHomalg"
      version: ">= 2014.12.08"
      url: "https://homalg-project.github.io/homalg_project/ToolsForHomalg/"
    - name: "MatricesForHomalg"
      version: ">= 2019.01.05"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "HomalgToCAS"
      version: ">= 2011.10.05"
      url: "https://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "RingsForHomalg"
      version: ">= 2013.04.16"
      url: "https://homalg-project.github.io/homalg_project/RingsForHomalg/"
    - name: "GradedRingForHomalg"
      version: ">= 2013.10.27"
      url: "https://homalg-project.github.io/homalg_project/GradedRingForHomalg/"
    - name: "Modules"
      version: ">= 2018.02.04"
      url: "https://homalg-project.github.io/homalg_project/Modules/"
    - name: "homalg"
      version: ">= 2013.06.23"
      url: "https://homalg-project.github.io/homalg_project/homalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://homalg-project.github.io/homalg_project/GradedModules/
readme: https://homalg-project.github.io/homalg_project/GradedModules/README
packageinfo: https://homalg-project.github.io/homalg_project/GradedModules/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/GradedModules-2019.09.02/GradedModules-2019.09.02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/GradedModules-2019.09.02/GradedModules-2019.09.02.zip

abstract: This homalg based package realizes the computability of the Abelian category of finitely presented graded modules over a computable graded ring

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
