name: ToricVarieties
version: 2020.04.25
date: 25/04/2020
description: A package to handle toric varieties

authors:
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io
    - name: Martin Bies
      url: mailto:martin.bies@alumni.uni-heidelberg.de

maintainers:
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io
    - name: Martin Bies
      url: mailto:martin.bies@alumni.uni-heidelberg.de

GAP: ">=4.7"

needed-pkgs:
    - name: "NConvex"
      version: ">= 2017.01.01"
      url: "https://homalg-project.github.io/NConvex"
    - name: "GradedRingForHomalg"
      version: ">=2020.04.25"
      url: "https://homalg-project.github.io/homalg_project/GradedRingForHomalg/"
    - name: "Modules"
      version: ">=2016.01.20"
      url: "https://homalg-project.github.io/homalg_project/Modules/"
    - name: "GradedModules"
      version: ">=2015.12.04"
      url: "https://homalg-project.github.io/homalg_project/GradedModules/"
    - name: "ToolsForHomalg"
      version: ">=2016.02.17"
      url: "https://homalg-project.github.io/homalg_project/ToolsForHomalg/"
    - name: "AutoDoc"
      version: ">=2016.02.16"
      url: "https://gap-packages.github.io/AutoDoc"

suggested-pkgs:
    - name: "4ti2Interface"
      version: ">=2020.04.25"
      url: "https://homalg-project.github.io/homalg_project/4ti2Interface/"
    - name: "TopcomInterface"
      version: ">=2019.06.15"
      url: "https://github.com/HereAround/TopcomInterface"

www: https://homalg-project.github.io/homalg_project/ToricVarieties/
readme: https://homalg-project.github.io/homalg_project/ToricVarieties/README
packageinfo: https://homalg-project.github.io/homalg_project/ToricVarieties/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/ToricVarieties-2020.04.25/ToricVarieties-2020.04.25.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/ToricVarieties-2020.04.25/ToricVarieties-2020.04.25.zip

abstract: ToricVarieties provides data structures to handle toric varieties by their commutative algebra structure and by their combinatorics. For combinatorics, it uses the Convex package. Its goal is to provide a suitable framework to work with toric varieties.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
