codecov:
  disable_default_path_fixes: true
  require_ci_to_pass: false
comment:
  after_n_builds: 15
flags:
  homalg:
    paths:
      - "homalg/"
  4ti2Interface:
    paths:
      - "4ti2Interface/"
  ExamplesForHomalg:
    paths:
      - "ExamplesForHomalg/"
  Gauss:
    paths:
      - "Gauss/"
  GaussForHomalg:
    paths:
      - "GaussForHomalg/"
  GradedModules:
    paths:
      - "GradedModules/"
  GradedRingForHomalg:
    paths:
      - "GradedRingForHomalg/"
  HomalgToCAS:
    paths:
      - "HomalgToCAS/"
  IO_ForHomalg:
    paths:
      - "IO_ForHomalg/"
  LocalizeRingForHomalg:
    paths:
      - "LocalizeRingForHomalg/"
  MatricesForHomalg:
    paths:
      - "MatricesForHomalg/"
  Modules:
    paths:
      - "Modules/"
  RingsForHomalg:
    paths:
      - "RingsForHomalg/"
  SCO:
    paths:
      - "SCO/"
  ToolsForHomalg:
    paths:
      - "ToolsForHomalg/"
