name: 4ti2Interface
version: 2019.09.03
date: 03/09/2019
description: A link to 4ti2

authors:
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io

maintainers:
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io

GAP: ">=4.7"

needed-pkgs:
    - name: "io"
      version: ">=4.2"
      url: "https://gap-packages.github.io/io"

suggested-pkgs:
    - name: "AutoDoc"
      version: ">=2013.08.22"
      url: "https://gap-packages.github.io/AutoDoc"

www: https://homalg-project.github.io/homalg_project/4ti2Interface/
readme: https://homalg-project.github.io/homalg_project/4ti2Interface/README
packageinfo: https://homalg-project.github.io/homalg_project/4ti2Interface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/4ti2Interface-2019.09.03/4ti2Interface-2019.09.03.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/4ti2Interface-2019.09.03/4ti2Interface-2019.09.03.zip

abstract: The <span class="pkgname">4ti2Interface</span> package provides an interface to 4ti2

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
