name: GaussForHomalg
version: 2019.01.10
date: 10/01/2019
description: Gauss functionality for the homalg project

authors:
    - name: Simon Goertzen
      url: http://wwwb.math.rwth-aachen.de/goertzen

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/

GAP: ">=4.7"

needed-pkgs:
    - name: "Gauss"
      version: ">= 2018.02.04"
      url: "http://homalg-project.github.io/homalg_project/Gauss/"
    - name: "MatricesForHomalg"
      version: ">= 2018.02.04"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/GaussForHomalg/
readme: http://homalg-project.github.io/homalg_project/GaussForHomalg/README
packageinfo: http://homalg-project.github.io/homalg_project/GaussForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/GaussForHomalg-2019.01.10/GaussForHomalg-2019.01.10.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/GaussForHomalg-2019.01.10/GaussForHomalg-2019.01.10.zip

abstract: The <span class="pkgname">GaussForHomalg</span> package provides Gauss functionality for <span class="pkgname">homalg</span> using the package <span class="pkgname">Gauss</span>

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
