name: GradedRingForHomalg
version: 2020.06.27
date: 27/06/2020
description: Endow Commutative Rings with an Abelian Grading

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io
    - name: Markus Kirschmer
      url: http://www.math.rwth-aachen.de/~Markus.Kirschmer/
    - name: Sebastian Jambor
      url: http://wwwb.math.rwth-aachen.de/~sebastian/
    - name: Markus Lange-Hegermann
      url: https://www.th-owl.de/eecs/fachbereich/team/markus-lange-hegermann/
    - name: Daniel Robertz
      url: http://wwwb.math.rwth-aachen.de/~daniel/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">= 2020.06.27"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "HomalgToCAS"
      version: ">= 2020.06.27"
      url: "https://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "RingsForHomalg"
      version: ">= 2020.06.27"
      url: "https://homalg-project.github.io/homalg_project/RingsForHomalg/"
    - name: "Modules"
      version: ">= 2018.02.04"
      url: "https://homalg-project.github.io/homalg_project/Modules/"
    - name: "homalg"
      version: ">=2011.08.16"
      url: "https://homalg-project.github.io/homalg_project/homalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "NConvex"
      version: "2020.03.02"
      url: "https://homalg-project.github.io/NConvex"
    - name: "4ti2Interface"
      version: "2019.09.03"
      url: "https://homalg-project.github.io/homalg_project/4ti2Interface/"

www: https://homalg-project.github.io/homalg_project/GradedRingForHomalg/
readme: https://homalg-project.github.io/homalg_project/GradedRingForHomalg/README
packageinfo: https://homalg-project.github.io/homalg_project/GradedRingForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/GradedRingForHomalg-2020.06.27/GradedRingForHomalg-2020.06.27.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/GradedRingForHomalg-2020.06.27/GradedRingForHomalg-2020.06.27.zip

abstract: This package is part of the homalg-project and manages graded rings.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
