name: ExamplesForHomalg
version: 2019.06.01
date: 01/06/2019
description: Examples for the GAP Package homalg

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Simon Görtzen
      url: https://www.linkedin.com/in/simongoertzen/
    - name: Markus Lange-Hegermann
      url: https://www.hs-owl.de/fb5/fachbereich/fachgebiete/md/team/prof-dr-markus-lange-hegermann.html

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">= 2019.01.07"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "HomalgToCAS"
      version: ">= 2011.08.25"
      url: "https://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "RingsForHomalg"
      version: ">= 2017.05.25"
      url: "https://homalg-project.github.io/homalg_project/RingsForHomalg/"
    - name: "Modules"
      version: ">= 2019.01.07"
      url: "https://homalg-project.github.io/homalg_project/Modules/"
    - name: "homalg"
      version: ">= 2015.06.01"
      url: "https://homalg-project.github.io/homalg_project/homalg/"
    - name: "GAPDoc"
      version: ">= 1.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://homalg-project.github.io/homalg_project/ExamplesForHomalg/
readme: https://homalg-project.github.io/homalg_project/ExamplesForHomalg/README
packageinfo: https://homalg-project.github.io/homalg_project/ExamplesForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/ExamplesForHomalg-2019.06.01/ExamplesForHomalg-2019.06.01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/ExamplesForHomalg-2019.06.01/ExamplesForHomalg-2019.06.01.zip

abstract: The <span class="pkgname">ExamplesForHomalg</span> package provides example scripts for the <span class="pkgname">homalg</span> package that can be used with several computer algebra systems

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
