name: Modules
version: 2020.02.05
date: 05/02/2020
description: A homalg based package for the Abelian category of finitely presented modules over computable rings

authors:
    - name: Thomas Bächler
      url: http://wwwb.math.rwth-aachen.de/~thomas/
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Florian Diebold
      url: mailto:diebold@mathematik.uni-kl.de
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io
    - name: Markus Lange-Hegermann
      url: https://www.hs-owl.de/fb5/fachbereich/fachgebiete/md/team/prof-dr-markus-lange-hegermann.html
    - name: Vinay Wagh
      url: http://www.iitg.ernet.in/vinay.wagh/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">=2019.01.08"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "ToolsForHomalg"
      version: ">=2013.04.12"
      url: "https://homalg-project.github.io/homalg_project/ToolsForHomalg/"
    - name: "homalg"
      version: ">=2019.09.01"
      url: "https://homalg-project.github.io/homalg_project/homalg/"
    - name: "GaussForHomalg"
      version: ">=2019.09.01"
      url: "https://homalg-project.github.io/homalg_project/GaussForHomalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://homalg-project.github.io/homalg_project/Modules/
readme: https://homalg-project.github.io/homalg_project/Modules/README
packageinfo: https://homalg-project.github.io/homalg_project/Modules/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/Modules-2020.02.05/Modules-2020.02.05.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/Modules-2020.02.05/Modules-2020.02.05.zip

abstract: The <span class="pkgname">Modules</span> package provides ring independent homological algebra functionality for the abelian category of finitely presented modules over computable rings

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
