name: HomalgToCAS
version: 2018.12.11
date: 11/12/2018
description: A window to the outer world

authors:
    - name: Thomas Bächler
      url: http://wwwb.math.rwth-aachen.de/~thomas/
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Simon Görtzen
      url: http://wwwb.math.rwth-aachen.de/~simon/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Vinay Wagh
      url: http://www.iitg.ernet.in/vinay.wagh/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Simon Görtzen
      url: http://wwwb.math.rwth-aachen.de/~simon/

GAP: ">=4.7"

needed-pkgs:
    - name: "IO"
      version: ">= 2.3"
      url: "https://gap-packages.github.io/io"
    - name: "MatricesForHomalg"
      version: ">= 2011.09.04"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/HomalgToCAS/
readme: http://homalg-project.github.io/homalg_project/HomalgToCAS/README
packageinfo: http://homalg-project.github.io/homalg_project/HomalgToCAS/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/HomalgToCAS-2018.12.11/HomalgToCAS-2018.12.11.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/HomalgToCAS-2018.12.11/HomalgToCAS-2018.12.11.zip

abstract: The <span class="pkgname">HomalgToCAS</span> package provides the first layer of abstraction  needed for <span class="pkgname">homalg</span> to access external computer algebra systems

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
